import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import { type ReactNode } from "react";
import { cookieToInitialState } from "wagmi";
import { getConfig } from "../wagmi";
import { Providers } from "./providers";
import { JetBrains_Mono } from "next/font/google";
import Header from "./components/Header";
import PageTransition from "./components/PageTransition";
import React from "react";
import StairTransition from "./components/StairTransition"

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

export const metadata: Metadata = {
  title: "Create Wagmi",
  description: "Generated by create-wagmi",
};

export default function RootLayout(props: { children: ReactNode }) {
  const initialState = cookieToInitialState(
    getConfig(),
    headers().get("cookie")
  );
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable} bg-primary`}>
        <PageTransition>
          <StairTransition />
          <Providers initialState={initialState}>
            <Header/>
            {props.children}
          </Providers>
        </PageTransition>
      </body>
    </html>
  );
}
