import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import { type ReactNode } from "react";
import { cookieToInitialState } from "wagmi";
import { getConfig } from "../wagmi";
import { Providers } from "./providers";
import { JetBrains_Mono } from "next/font/google";
import Header from "@/components/ui/Header";
import PageTransition from "@/components/ui/PageTransition";
import React from "react";
import StairTransition from "@/components/ui/StairTransition";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

export const metadata: Metadata = {
  title: "Create stellar",
  description: "Generated by stellar",
};

export default async function RootLayout(props: { children: ReactNode }) { // Añadir async
  const headersList = await headers(); // Esperar las cabeceras
  const initialState = cookieToInitialState(
    getConfig(),
    headersList.get("cookie") // Usar headersList en lugar de headers()
  );
  
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable} `}>
        <PageTransition>
          <StairTransition />
          <Providers initialState={initialState}> {/* Asegurar que Providers acepte esta prop */}
            <Header/>
            {props.children}
          </Providers>
        </PageTransition>
      </body>
    </html>
  );
}